services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dynamicuser
      POSTGRES_PASSWORD: dynamicpass
      POSTGRES_DB: dynamicnfc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  springboot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dynamicnfc-springboot-app:latest
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dynamicnfc
      SPRING_DATASOURCE_USERNAME: dynamicuser
      SPRING_DATASOURCE_PASSWORD: dynamicpass
      SPRING_PROFILES_ACTIVE: production
      SERVER_FORWARD_HEADERS_STRATEGY: framework
      DOCUSIGN_RSA_KEY_PATH: /app/docusign-private.key
    ports:
      - "8080:8080"
    networks:
      - backend_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dynamicnfc-frontend:latest
    depends_on:
      - springboot-app
    networks:
      - backend_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - springboot-app
    networks:
      - backend_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend_net:
