import React from 'react';
import { useLanguage } from '../../i18n';
import SEO from '../../components/SEO/SEO';

const TR = {
  en: {
    title: 'Privacy Policy',
    seoDesc: 'DynamicNFC Privacy Policy',
    updated: 'Last updated: October 2026',
    sections: [
      { heading: '1. Information We Collect', body: 'We collect information you provide directly (name, email, account data) and data generated through your use of the Service (analytics, device info, IP addresses). NFC card tap data is collected to provide analytics features.' },
      { heading: '2. How We Use Your Information', body: 'We use collected data to provide and improve the Service, send account notifications, generate analytics dashboards, and ensure platform security. We do not sell your personal data to third parties.' },
      { heading: '3. Data Storage & Security', body: 'Your data is stored on Firebase (Google Cloud) infrastructure with industry-standard encryption. We implement appropriate security measures including encrypted connections and secure authentication.' },
      { heading: '4. Cookies & Tracking', body: 'We use essential cookies for authentication and optional analytics cookies (with your consent) to understand usage patterns. You can manage cookie preferences at any time through our cookie consent banner.' },
      { heading: '5. Third-Party Services', body: 'We integrate with third-party services including Firebase Authentication, Google Analytics, and Sentry for error monitoring. Each service has its own privacy policy governing data they process.' },
      { heading: '6. Your Rights', body: 'You may request access to, correction of, or deletion of your personal data at any time by contacting us. You can delete your account and associated data through your dashboard settings.' },
      { heading: '7. PIPEDA Compliance', body: 'We comply with Canada\'s Personal Information Protection and Electronic Documents Act (PIPEDA). We obtain consent for data collection, limit collection to necessary purposes, and protect data with appropriate safeguards.' },
      { heading: '8. Who We Are (Data Controller)', body: 'DynamicNFC is operated by NFC Software Systems Inc. (British Columbia, Canada, registration no. BC1545283), which is the controller of the personal data described in this policy. Contact: info@dynamicnfc.help.' },
      { heading: '9. Legal Bases for Processing (EU / EEA)', body: 'If you are in the European Union or the European Economic Area, including Italy, the EU General Data Protection Regulation (GDPR) applies to our processing of your personal data. We process it on these legal bases: performance of a contract (creating and running your account and providing the Service); your consent (analytics cookies and marketing messages, which you can withdraw at any time); and our legitimate interests (keeping the Service secure, preventing misuse, and improving it).' },
      { heading: '10. Your Rights Under the GDPR', body: 'In addition to the rights in section 6, you have the right to restrict or object to processing, the right to data portability, and the right to withdraw consent at any time without affecting earlier processing. You also have the right to lodge a complaint with your local supervisory authority; in Italy this is the Garante per la protezione dei dati personali (www.garanteprivacy.it). We respond to requests within one month.' },
      { heading: '11. International Data Transfers', body: 'Our database is hosted in Canada (Montréal). Some of our service providers, including Google (Firebase, Google Analytics) and Sentry, may process data in Canada, the United States, or other countries. Transfers from the EU to Canada rely on the European Commission\'s adequacy decision for organisations subject to PIPEDA. For transfers to other countries we rely on appropriate safeguards, such as the European Commission\'s Standard Contractual Clauses.' },
      { heading: '12. Data Retention', body: 'We keep personal data only for as long as needed for the purposes described in this policy: account data for as long as your account is active, and after that only for as long as the law requires. Inactive demo workspaces are deleted after a period of inactivity.' },
      { heading: '13. Profiling & Automated Decisions', body: 'The Service generates engagement scores from interactions with a private portal (for example pages viewed or documents downloaded) to help our business customers\' sales teams prioritise follow-up. We do not make decisions that produce legal or similarly significant effects on you solely by automated means.' },
      { heading: '14. When We Act on Behalf of Our Customers', body: 'When a business customer uses DynamicNFC to invite and engage its own clients, that customer decides why and how the data is used and is the controller; we process the data on its behalf as a processor. In that case, please contact the business that invited you first. A data processing agreement is available to customers on request.' },
      { heading: '15. Contact', body: 'For privacy inquiries, contact our data protection team at info@dynamicnfc.help.' },
    ],
  },
  it: {
    title: 'Informativa sulla privacy',
    seoDesc: 'Informativa sulla privacy di DynamicNFC',
    updated: 'Ultimo aggiornamento: ottobre 2026',
    sections: [
      { heading: '1. Informazioni che raccogliamo', body: 'Raccogliamo le informazioni che fornisci direttamente (nome, email, dati dell\'account) e i dati generati dal tuo utilizzo del Servizio (analisi, informazioni sul dispositivo, indirizzi IP). I dati dei tap delle card NFC vengono raccolti per fornire le funzionalità di analisi.' },
      { heading: '2. Come utilizziamo le tue informazioni', body: 'Utilizziamo i dati raccolti per fornire e migliorare il Servizio, inviare notifiche relative all\'account, generare dashboard di analisi e garantire la sicurezza della piattaforma. Non vendiamo i tuoi dati personali a terze parti.' },
      { heading: '3. Conservazione e sicurezza dei dati', body: 'I tuoi dati sono conservati sull\'infrastruttura Firebase (Google Cloud) con crittografia conforme agli standard di settore. Adottiamo misure di sicurezza adeguate, tra cui connessioni crittografate e autenticazione sicura.' },
      { heading: '4. Cookie e tracciamento', body: 'Utilizziamo cookie essenziali per l\'autenticazione e cookie analitici facoltativi (con il tuo consenso) per comprendere i modelli di utilizzo. Puoi gestire le preferenze sui cookie in qualsiasi momento tramite il nostro banner di consenso ai cookie.' },
      { heading: '5. Servizi di terze parti', body: 'Ci integriamo con servizi di terze parti, tra cui Firebase Authentication, Google Analytics e Sentry per il monitoraggio degli errori. Ogni servizio ha una propria informativa sulla privacy che disciplina i dati che tratta.' },
      { heading: '6. I tuoi diritti', body: 'Puoi richiedere in qualsiasi momento l\'accesso, la rettifica o la cancellazione dei tuoi dati personali contattandoci. Puoi eliminare il tuo account e i dati associati tramite le impostazioni della tua dashboard.' },
      { heading: '7. Conformità al PIPEDA', body: 'Rispettiamo il Personal Information Protection and Electronic Documents Act (PIPEDA) del Canada. Otteniamo il consenso per la raccolta dei dati, limitiamo la raccolta alle finalità necessarie e proteggiamo i dati con garanzie adeguate.' },
      { heading: '8. Chi siamo (Titolare del trattamento)', body: 'DynamicNFC è gestito da NFC Software Systems Inc. (British Columbia, Canada, n. di registrazione BC1545283), titolare del trattamento dei dati personali descritti nella presente informativa. Contatto: info@dynamicnfc.help.' },
      { heading: '9. Basi giuridiche del trattamento (UE / SEE)', body: 'Se ti trovi nell\'Unione europea o nello Spazio economico europeo, Italia compresa, al trattamento dei tuoi dati personali si applica il Regolamento generale sulla protezione dei dati (GDPR). Trattiamo i dati sulle seguenti basi giuridiche: esecuzione di un contratto (creazione e gestione del tuo account e fornitura del Servizio); il tuo consenso (cookie analitici e comunicazioni di marketing, revocabile in qualsiasi momento); il nostro legittimo interesse (mantenere il Servizio sicuro, prevenire gli abusi e migliorarlo).' },
      { heading: '10. I tuoi diritti ai sensi del GDPR', body: 'Oltre ai diritti indicati nella sezione 6, hai il diritto di ottenere la limitazione del trattamento o di opporti ad esso, il diritto alla portabilità dei dati e il diritto di revocare il consenso in qualsiasi momento, senza pregiudicare il trattamento precedente. Hai inoltre il diritto di proporre reclamo all\'autorità di controllo competente; in Italia è il Garante per la protezione dei dati personali (www.garanteprivacy.it). Rispondiamo alle richieste entro un mese.' },
      { heading: '11. Trasferimenti internazionali di dati', body: 'Il nostro database è ospitato in Canada (Montréal). Alcuni dei nostri fornitori di servizi, tra cui Google (Firebase, Google Analytics) e Sentry, possono trattare i dati in Canada, negli Stati Uniti o in altri Paesi. I trasferimenti dall\'UE al Canada si basano sulla decisione di adeguatezza della Commissione europea per le organizzazioni soggette al PIPEDA. Per i trasferimenti verso altri Paesi ci basiamo su garanzie adeguate, come le Clausole contrattuali tipo della Commissione europea.' },
      { heading: '12. Conservazione dei dati', body: 'Conserviamo i dati personali solo per il tempo necessario alle finalità descritte nella presente informativa: i dati dell\'account finché l\'account è attivo e, successivamente, solo per il tempo richiesto dalla legge. Gli spazi di lavoro demo inattivi vengono eliminati dopo un periodo di inattività.' },
      { heading: '13. Profilazione e decisioni automatizzate', body: 'Il Servizio genera punteggi di coinvolgimento a partire dalle interazioni con un portale privato (ad esempio pagine visualizzate o documenti scaricati) per aiutare i team commerciali dei nostri clienti aziendali a dare priorità ai contatti. Non adottiamo decisioni che producano effetti giuridici o effetti analogamente significativi su di te basate unicamente su trattamenti automatizzati.' },
      { heading: '14. Quando agiamo per conto dei nostri clienti', body: 'Quando un cliente aziendale utilizza DynamicNFC per invitare e coinvolgere i propri clienti, è tale cliente a decidere finalità e modalità del trattamento ed è il titolare; noi trattiamo i dati per suo conto in qualità di responsabile del trattamento. In tal caso, rivolgiti innanzitutto all\'azienda che ti ha invitato. Un accordo sul trattamento dei dati è disponibile per i clienti su richiesta.' },
      { heading: '15. Contatti', body: 'Per richieste relative alla privacy, contatta il nostro team per la protezione dei dati all\'indirizzo info@dynamicnfc.help.' },
    ],
  },
  fr: {
    title: 'Politique de confidentialité',
    seoDesc: 'Politique de confidentialité de DynamicNFC',
    updated: 'Dernière mise à jour : octobre 2026',
    sections: [
      { heading: '1. Renseignements que nous recueillons', body: 'Nous recueillons les renseignements que vous fournissez directement (nom, courriel, données de compte) ainsi que les données générées par votre utilisation du Service (analyses, renseignements sur l\'appareil, adresses IP). Les données de tap des cartes NFC sont recueillies afin de fournir les fonctionnalités d\'analyse.' },
      { heading: '2. Comment nous utilisons vos renseignements', body: 'Nous utilisons les données recueillies pour fournir et améliorer le Service, envoyer des notifications de compte, générer des tableaux de bord d\'analyse et assurer la sécurité de la plateforme. Nous ne vendons pas vos données personnelles à des tiers.' },
      { heading: '3. Stockage et sécurité des données', body: 'Vos données sont stockées sur l\'infrastructure Firebase (Google Cloud) avec un chiffrement conforme aux normes de l\'industrie. Nous mettons en œuvre des mesures de sécurité appropriées, notamment des connexions chiffrées et une authentification sécurisée.' },
      { heading: '4. Témoins et suivi', body: 'Nous utilisons des témoins essentiels pour l\'authentification et des témoins d\'analyse facultatifs (avec votre consentement) pour comprendre les habitudes d\'utilisation. Vous pouvez gérer vos préférences en matière de témoins à tout moment au moyen de notre bannière de consentement aux témoins.' },
      { heading: '5. Services tiers', body: 'Nous intégrons des services tiers, notamment Firebase Authentication, Google Analytics et Sentry pour la surveillance des erreurs. Chaque service a sa propre politique de confidentialité régissant les données qu\'il traite.' },
      { heading: '6. Vos droits', body: 'Vous pouvez demander l\'accès à vos données personnelles, leur rectification ou leur suppression à tout moment en communiquant avec nous. Vous pouvez supprimer votre compte et les données associées dans les paramètres de votre dashboard.' },
      { heading: '7. Conformité à la LPRPDE', body: 'Nous nous conformons à la Loi sur la protection des renseignements personnels et les documents électroniques (LPRPDE) du Canada. Nous obtenons le consentement pour la collecte de données, limitons la collecte aux fins nécessaires et protégeons les données au moyen de mesures de protection appropriées.' },
      { heading: '8. Qui nous sommes (responsable du traitement)', body: 'DynamicNFC est exploité par NFC Software Systems Inc. (Colombie-Britannique, Canada, numéro d\'enregistrement BC1545283), responsable du traitement des données personnelles décrites dans la présente politique. Contact : info@dynamicnfc.help.' },
      { heading: '9. Fondements juridiques du traitement (UE / EEE)', body: 'Si vous vous trouvez dans l\'Union européenne ou l\'Espace économique européen, y compris en Italie, le Règlement général sur la protection des données (RGPD) s\'applique au traitement de vos données personnelles. Nous les traitons sur les fondements suivants : l\'exécution d\'un contrat (création et gestion de votre compte et fourniture du Service) ; votre consentement (témoins d\'analyse et messages de marketing, que vous pouvez retirer à tout moment) ; et nos intérêts légitimes (assurer la sécurité du Service, prévenir les abus et l\'améliorer).' },
      { heading: '10. Vos droits en vertu du RGPD', body: 'En plus des droits prévus à la section 6, vous avez le droit d\'obtenir la limitation du traitement ou de vous y opposer, le droit à la portabilité des données et le droit de retirer votre consentement à tout moment, sans incidence sur le traitement antérieur. Vous avez également le droit de déposer une plainte auprès de votre autorité de contrôle ; en Italie, il s\'agit du Garante per la protezione dei dati personali (www.garanteprivacy.it). Nous répondons aux demandes dans un délai d\'un mois.' },
      { heading: '11. Transferts internationaux de données', body: 'Notre base de données est hébergée au Canada (Montréal). Certains de nos fournisseurs de services, dont Google (Firebase, Google Analytics) et Sentry, peuvent traiter des données au Canada, aux États-Unis ou dans d\'autres pays. Les transferts de l\'UE vers le Canada reposent sur la décision d\'adéquation de la Commission européenne visant les organisations assujetties à la LPRPDE (PIPEDA). Pour les transferts vers d\'autres pays, nous nous appuyons sur des garanties appropriées, telles que les clauses contractuelles types de la Commission européenne.' },
      { heading: '12. Conservation des données', body: 'Nous ne conservons les données personnelles que le temps nécessaire aux fins décrites dans la présente politique : les données de compte tant que votre compte est actif, puis uniquement aussi longtemps que la loi l\'exige. Les espaces de travail de démonstration inactifs sont supprimés après une période d\'inactivité.' },
      { heading: '13. Profilage et décisions automatisées', body: 'Le Service génère des scores d\'engagement à partir des interactions avec un portail privé (par exemple les pages consultées ou les documents téléchargés) afin d\'aider les équipes de vente de nos clients professionnels à prioriser leurs suivis. Nous ne prenons aucune décision produisant des effets juridiques ou des effets significatifs similaires à votre égard sur le seul fondement d\'un traitement automatisé.' },
      { heading: '14. Lorsque nous agissons pour le compte de nos clients', body: 'Lorsqu\'un client professionnel utilise DynamicNFC pour inviter et mobiliser ses propres clients, c\'est ce client qui détermine les finalités et les moyens du traitement et qui est le responsable du traitement ; nous traitons les données pour son compte en qualité de sous-traitant. Dans ce cas, veuillez d\'abord communiquer avec l\'entreprise qui vous a invité. Un accord de traitement des données est offert aux clients sur demande.' },
      { heading: '15. Contact', body: 'Pour toute question relative à la confidentialité, communiquez avec notre équipe de protection des données à info@dynamicnfc.help.' },
    ],
  },
  es: {
    title: 'Política de privacidad',
    seoDesc: 'Política de privacidad de DynamicNFC',
    updated: 'Última actualización: octubre de 2026',
    sections: [
      { heading: '1. Información que recopilamos', body: 'Recopilamos la información que proporcionas directamente (nombre, correo electrónico, datos de la cuenta) y los datos generados por tu uso del Servicio (analíticas, información del dispositivo, direcciones IP). Los datos de tap de las tarjetas NFC se recopilan para ofrecer las funciones de analítica.' },
      { heading: '2. Cómo usamos tu información', body: 'Usamos los datos recopilados para prestar y mejorar el Servicio, enviar notificaciones de la cuenta, generar dashboards de analítica y garantizar la seguridad de la plataforma. No vendemos tus datos personales a terceros.' },
      { heading: '3. Almacenamiento y seguridad de los datos', body: 'Tus datos se almacenan en la infraestructura de Firebase (Google Cloud) con cifrado estándar de la industria. Implementamos medidas de seguridad adecuadas, incluidas conexiones cifradas y autenticación segura.' },
      { heading: '4. Cookies y seguimiento', body: 'Usamos cookies esenciales para la autenticación y cookies de analítica opcionales (con tu consentimiento) para comprender los patrones de uso. Puedes gestionar tus preferencias de cookies en cualquier momento a través de nuestro banner de consentimiento de cookies.' },
      { heading: '5. Servicios de terceros', body: 'Nos integramos con servicios de terceros, entre ellos Firebase Authentication, Google Analytics y Sentry para el monitoreo de errores. Cada servicio tiene su propia política de privacidad que rige los datos que procesa.' },
      { heading: '6. Tus derechos', body: 'Puedes solicitar el acceso, la corrección o la eliminación de tus datos personales en cualquier momento contactándonos. Puedes eliminar tu cuenta y los datos asociados desde la configuración de tu dashboard.' },
      { heading: '7. Cumplimiento de PIPEDA', body: 'Cumplimos con la Ley de Protección de la Información Personal y los Documentos Electrónicos de Canadá (PIPEDA). Obtenemos el consentimiento para la recopilación de datos, limitamos la recopilación a los fines necesarios y protegemos los datos con salvaguardas adecuadas.' },
      { heading: '8. Quiénes somos (responsable del tratamiento)', body: 'DynamicNFC es operado por NFC Software Systems Inc. (Columbia Británica, Canadá, n.º de registro BC1545283), responsable del tratamiento de los datos personales descritos en esta política. Contacto: info@dynamicnfc.help.' },
      { heading: '9. Bases legales del tratamiento (UE / EEE)', body: 'Si te encuentras en la Unión Europea o en el Espacio Económico Europeo, incluida Italia, el Reglamento General de Protección de Datos (RGPD) se aplica al tratamiento de tus datos personales. Los tratamos con estas bases legales: la ejecución de un contrato (crear y gestionar tu cuenta y prestar el Servicio); tu consentimiento (cookies analíticas y mensajes de marketing, que puedes retirar en cualquier momento); y nuestros intereses legítimos (mantener el Servicio seguro, prevenir el uso indebido y mejorarlo).' },
      { heading: '10. Tus derechos conforme al RGPD', body: 'Además de los derechos de la sección 6, tienes derecho a solicitar la limitación del tratamiento o a oponerte a él, derecho a la portabilidad de los datos y derecho a retirar tu consentimiento en cualquier momento, sin afectar el tratamiento anterior. También tienes derecho a presentar una reclamación ante tu autoridad de control; en Italia es el Garante per la protezione dei dati personali (www.garanteprivacy.it). Respondemos a las solicitudes en el plazo de un mes.' },
      { heading: '11. Transferencias internacionales de datos', body: 'Nuestra base de datos está alojada en Canadá (Montreal). Algunos de nuestros proveedores de servicios, entre ellos Google (Firebase, Google Analytics) y Sentry, pueden tratar datos en Canadá, Estados Unidos u otros países. Las transferencias de la UE a Canadá se basan en la decisión de adecuación de la Comisión Europea para las organizaciones sujetas a PIPEDA. Para las transferencias a otros países nos basamos en garantías adecuadas, como las Cláusulas Contractuales Tipo de la Comisión Europea.' },
      { heading: '12. Conservación de datos', body: 'Conservamos los datos personales solo durante el tiempo necesario para los fines descritos en esta política: los datos de la cuenta mientras tu cuenta esté activa y, después, solo durante el tiempo que exija la ley. Los espacios de trabajo de demostración inactivos se eliminan tras un periodo de inactividad.' },
      { heading: '13. Elaboración de perfiles y decisiones automatizadas', body: 'El Servicio genera puntuaciones de interacción a partir de la actividad en un portal privado (por ejemplo, páginas vistas o documentos descargados) para ayudar a los equipos de ventas de nuestros clientes empresariales a priorizar su seguimiento. No tomamos decisiones que produzcan efectos jurídicos o efectos significativos similares sobre ti basadas únicamente en un tratamiento automatizado.' },
      { heading: '14. Cuando actuamos por cuenta de nuestros clientes', body: 'Cuando un cliente empresarial usa DynamicNFC para invitar y atender a sus propios clientes, ese cliente decide para qué y cómo se usan los datos y es el responsable del tratamiento; nosotros tratamos los datos por su cuenta como encargado del tratamiento. En ese caso, contacta primero a la empresa que te invitó. Los clientes pueden solicitar un acuerdo de tratamiento de datos.' },
      { heading: '15. Contacto', body: 'Para consultas sobre privacidad, contacta a nuestro equipo de protección de datos en info@dynamicnfc.help.' },
    ],
  },
  ar: {
    title: 'سياسة الخصوصية',
    seoDesc: 'سياسة الخصوصية لـ DynamicNFC',
    updated: 'آخر تحديث: أكتوبر ٢٠٢٦',
    sections: [
      { heading: '١. المعلومات التي نجمعها', body: 'نجمع المعلومات التي تقدمها مباشرة (الاسم، البريد الإلكتروني، بيانات الحساب) والبيانات المُنشأة من خلال استخدامك للخدمة (التحليلات، معلومات الجهاز، عناوين IP). يتم جمع بيانات نقر بطاقات NFC لتوفير ميزات التحليلات.' },
      { heading: '٢. كيف نستخدم معلوماتك', body: 'نستخدم البيانات المجمعة لتقديم الخدمة وتحسينها، وإرسال إشعارات الحساب، وإنشاء لوحات التحليلات، وضمان أمان المنصة. لا نبيع بياناتك الشخصية لأطراف ثالثة.' },
      { heading: '٣. تخزين البيانات والأمان', body: 'يتم تخزين بياناتك على بنية Firebase (Google Cloud) التحتية مع تشفير بمعايير الصناعة. نطبق إجراءات أمان مناسبة بما في ذلك الاتصالات المشفرة والمصادقة الآمنة.' },
      { heading: '٤. ملفات تعريف الارتباط والتتبع', body: 'نستخدم ملفات تعريف الارتباط الأساسية للمصادقة وملفات تعريف الارتباط التحليلية الاختيارية (بموافقتك) لفهم أنماط الاستخدام. يمكنك إدارة تفضيلات ملفات تعريف الارتباط في أي وقت.' },
      { heading: '٥. خدمات الطرف الثالث', body: 'نتكامل مع خدمات الطرف الثالث بما في ذلك Firebase Authentication و Google Analytics و Sentry لمراقبة الأخطاء. لكل خدمة سياسة خصوصية خاصة بها.' },
      { heading: '٦. حقوقك', body: 'يمكنك طلب الوصول إلى بياناتك الشخصية أو تصحيحها أو حذفها في أي وقت بالاتصال بنا. يمكنك حذف حسابك والبيانات المرتبطة به من خلال إعدادات لوحة التحكم.' },
      { heading: '٧. الامتثال لـ PIPEDA', body: 'نمتثل لقانون حماية المعلومات الشخصية والوثائق الإلكترونية الكندي (PIPEDA). نحصل على الموافقة لجمع البيانات، ونحد من الجمع للأغراض الضرورية، ونحمي البيانات بضمانات مناسبة.' },
      { heading: '٨. من نحن (المتحكم في البيانات)', body: 'تُشغِّل DynamicNFC شركة NFC Software Systems Inc. (كولومبيا البريطانية، كندا، رقم التسجيل BC1545283)، وهي المتحكم في البيانات الشخصية الموصوفة في هذه السياسة. للتواصل: info@dynamicnfc.help.' },
      { heading: '٩. الأسس القانونية للمعالجة (الاتحاد الأوروبي / المنطقة الاقتصادية الأوروبية)', body: 'إذا كنت في الاتحاد الأوروبي أو المنطقة الاقتصادية الأوروبية، بما في ذلك إيطاليا، فإن اللائحة العامة لحماية البيانات (GDPR) تنطبق على معالجتنا لبياناتك الشخصية. نعالج البيانات استنادًا إلى الأسس القانونية التالية: تنفيذ العقد (إنشاء حسابك وإدارته وتقديم الخدمة)؛ موافقتك (ملفات تعريف الارتباط التحليلية والرسائل التسويقية، ويمكنك سحبها في أي وقت)؛ ومصالحنا المشروعة (الحفاظ على أمان الخدمة ومنع إساءة استخدامها وتحسينها).' },
      { heading: '١٠. حقوقك بموجب اللائحة العامة لحماية البيانات', body: 'إضافةً إلى الحقوق الواردة في القسم ٦، يحق لك طلب تقييد المعالجة أو الاعتراض عليها، ويحق لك نقل بياناتك، وسحب موافقتك في أي وقت دون أن يؤثر ذلك في المعالجة السابقة. ويحق لك كذلك تقديم شكوى إلى السلطة الرقابية المختصة في بلدك؛ وهي في إيطاليا Garante per la protezione dei dati personali (www.garanteprivacy.it). نرد على الطلبات خلال شهر واحد.' },
      { heading: '١١. النقل الدولي للبيانات', body: 'قاعدة بياناتنا مستضافة في كندا (مونتريال). قد يعالج بعض مزوّدي خدماتنا، ومنهم Google (Firebase و Google Analytics) و Sentry، البيانات في كندا أو الولايات المتحدة أو بلدان أخرى. يستند نقل البيانات من الاتحاد الأوروبي إلى كندا إلى قرار الكفاية الصادر عن المفوضية الأوروبية بشأن المؤسسات الخاضعة لقانون PIPEDA. أما النقل إلى بلدان أخرى فنستند فيه إلى ضمانات مناسبة، مثل البنود التعاقدية النموذجية الصادرة عن المفوضية الأوروبية.' },
      { heading: '١٢. الاحتفاظ بالبيانات', body: 'نحتفظ بالبيانات الشخصية فقط للمدة اللازمة للأغراض الموصوفة في هذه السياسة: بيانات الحساب ما دام حسابك نشطًا، وبعد ذلك فقط للمدة التي يقتضيها القانون. تُحذف مساحات العمل التجريبية غير النشطة بعد فترة من عدم النشاط.' },
      { heading: '١٣. التنميط والقرارات الآلية', body: 'تُنشئ الخدمة درجات تفاعل استنادًا إلى التفاعلات مع البوابة الخاصة (مثل الصفحات التي تمت مشاهدتها أو المستندات التي تم تنزيلها) لمساعدة فرق المبيعات لدى عملائنا من الشركات على تحديد أولويات المتابعة. لا نتخذ قرارات تترتب عليها آثار قانونية أو آثار مماثلة في أهميتها بحقك استنادًا إلى المعالجة الآلية وحدها.' },
      { heading: '١٤. عندما نعمل نيابةً عن عملائنا', body: 'عندما يستخدم عميل من الشركات DynamicNFC لدعوة عملائه والتفاعل معهم، فإن ذلك العميل هو من يحدد أغراض استخدام البيانات ووسائله وهو المتحكم في البيانات؛ ونحن نعالج البيانات نيابةً عنه بصفتنا معالجًا. في هذه الحالة، يُرجى التواصل أولًا مع الشركة التي دعتك. تتوفر اتفاقية معالجة البيانات للعملاء عند الطلب.' },
      { heading: '١٥. الاتصال', body: 'لاستفسارات الخصوصية، تواصل مع فريق حماية البيانات لدينا على info@dynamicnfc.help.' },
    ],
  },
};

const Privacy = () => {
  const { lang } = useLanguage();
  const isRTL = lang === 'ar';
  const t = TR[lang] || TR.en;

  return (
    <div dir={isRTL ? 'rtl' : 'ltr'} style={{ maxWidth: '720px', margin: '0 auto', padding: '3rem 1.5rem', color: 'var(--text)' }}>
      <SEO title={t.title} description={t.seoDesc} path="/privacy" />
      <h1 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: '.5rem' }}>{t.title}</h1>
      <p style={{ color: 'var(--muted)', marginBottom: '2rem', fontSize: '.9rem' }}>{t.updated}</p>
      {t.sections.map((s, i) => (
        <section key={i} style={{ marginBottom: '1.5rem' }}>
          <h2 style={{ fontSize: '1.15rem', fontWeight: 600, marginBottom: '.4rem' }}>{s.heading}</h2>
          <p style={{ lineHeight: 1.7, color: 'var(--text2)' }}>{s.body}</p>
        </section>
      ))}
    </div>
  );
};

export default Privacy;
