spring.application.name=backend
spring.datasource.url=jdbc:postgresql://3.128.244.219:5432/dynamicnfc
spring.datasource.username=dynamicuser
spring.datasource.password=dynamicpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Allow large uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dynamicnfc3@gmail.com
spring.mail.password=123456T!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true