spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dynamicnfc
spring.datasource.username=dynamicuser
spring.datasource.password=dynamicpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true